/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package QuickMeal.Vistas;

import QuickMeal.Accesos.AccesoProducto;
import QuickMeal.Accesos.Mensaje;
import QuickMeal.Objetos.ObjetoProducto;
import QuickMeal.Servicios.ServicioLeerArchivoExcel;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Megabytes Soluciones Integrales Guatemala
 */
public class BaseDeDatosExportarCatalogoDeProductos extends javax.swing.JInternalFrame {

    Mensaje mensaje = new Mensaje();
    ObjetoProducto producto = new ObjetoProducto();
    AccesoProducto acceso = new AccesoProducto();
    ArrayList<ObjetoProducto> lista = new ArrayList();
    DefaultTableModel modelo = new DefaultTableModel();
    int i = 0;
    
    /**
     * Creates new form wdwBaseDeDatosExportarCatalogoDeProductos
     */
    public BaseDeDatosExportarCatalogoDeProductos() {
        initComponents();
        mostrarRegistrosGuardados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatosExcel = new javax.swing.JTable();
        btnGuardarArchivo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Exportar Catalogo de Productos");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/exportar.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setPreferredSize(new java.awt.Dimension(900, 500));

        tblDatosExcel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Producto", "Id Proveedor", "Descripcion", "Costo", "Cantidad", "Unidad Medida", "Caducidad", "Minimo"
            }
        ));
        jScrollPane1.setViewportView(tblDatosExcel);

        btnGuardarArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/guardar.png"))); // NOI18N
        btnGuardarArchivo.setText("Guardar Archivo");
        btnGuardarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarArchivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardarArchivo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarArchivo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarRegistrosGuardados() {
        i = 0;
        modelo.setRowCount(0);
        lista = acceso.retornaProductos();
        modelo.addColumn("Id Producto");
        modelo.addColumn("Id Proveedor");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Costo");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Unidad Medida");
        modelo.addColumn("Caducidad");
        modelo.addColumn("minimo");
        modelo.setRowCount(lista.size());
        for(ObjetoProducto n : lista){
            modelo.setValueAt(n.getId_producto(), i, 0);
            modelo.setValueAt(n.getId_proveedor(), i, 1);
            modelo.setValueAt(n.getDescripcion_producto(), i, 2);
            modelo.setValueAt(n.getCosto_producto(), i, 3);
            modelo.setValueAt(n.getCantidad_producto(), i, 4);
            modelo.setValueAt(n.getUnidad_medida_producto(), i, 5);
            modelo.setValueAt(n.getCaducidad_producto(), i, 6);
            modelo.setValueAt(n.getMinimo_producto(), i, 7);
            i++;
        }
        tblDatosExcel.setModel(modelo);
    }

    private void btnGuardarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarArchivoActionPerformed

        JFileChooser flcArchivo = new JFileChooser(".");
        flcArchivo.setApproveButtonText("Guardar");
        int estado = flcArchivo.showOpenDialog(null);

        if (estado == JFileChooser.APPROVE_OPTION) {

            File archivo_seleccionado = flcArchivo.getSelectedFile();
            String direccion = archivo_seleccionado.getParent() + "\\" + archivo_seleccionado.getName();

            try {
                ServicioLeerArchivoExcel archivo = new ServicioLeerArchivoExcel();
                archivo.escribir_archivo_excel(tblDatosExcel, new File(direccion));
                mensaje.manipulacionExcepciones("informacion", "El archivo fue generado con exito");
            } catch (IOException error) {
                mensaje.manipulacionExcepciones("critico", "No se ha podido crear el archivo -> " + error);
            }

        } else if (estado == JFileChooser.CANCEL_OPTION) {
            System.out.println("Se a cancelado la operacion");
        }
    }//GEN-LAST:event_btnGuardarArchivoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarArchivo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDatosExcel;
    // End of variables declaration//GEN-END:variables
}
