/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package QuickMeal.Vistas;

import QuickMeal.Accesos.AccesoReporteVentasConsolidado;
import QuickMeal.Accesos.AccesoServicio;
import QuickMeal.Accesos.Mensaje;
import QuickMeal.Objetos.ObjetoServicio;
import QuickMeal.Objetos.ObjetoVentaConsolidado;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Megabyte Soluciones Integrales Guatemala
 */


public class BaseDeDatosVentasConsolidado extends javax.swing.JInternalFrame {

    AccesoReporteVentasConsolidado acceso = new AccesoReporteVentasConsolidado();
    AccesoServicio acceso_servicio = new AccesoServicio();
    ArrayList<ObjetoVentaConsolidado> lista = new ArrayList();
    ArrayList<ObjetoServicio> lista_servicio = new ArrayList();
    Mensaje mensaje = new Mensaje();
    
    /**
     * Creates new form wdwBaseDeDAtosHistorialDeVentas
     */
    public BaseDeDatosVentasConsolidado() {
        initComponents();
    }
    
    private void mostrarOrdenes(String inicio, String fin, String codigo){
        
        DefaultTableModel tabla = new DefaultTableModel();
        lista = acceso.ejecutar(inicio, fin, codigo);
        
        tabla.addColumn("Codigo");
        tabla.addColumn("Centro de Costo");
        tabla.addColumn("Cuenta");
        tabla.addColumn("Nombre");
        tabla.addColumn("Empresa");
        tabla.addColumn("No. Vale");
        tabla.addColumn("Fecha");
        tabla.addColumn("Propina");
        tabla.addColumn("Venta");
        tabla.addColumn("Descuento");
        tabla.addColumn("Extra");
        tabla.addColumn("Total");
        tabla.addColumn("Pago");
        tabla.addColumn("Empleado");
        tabla.addColumn("Servicio");
        tabla.addColumn("Costo");
        
        tabla.setRowCount(lista.size());
        int i = 0;
        
        for(ObjetoVentaConsolidado n : lista){
            tabla.setValueAt(n.getCodigo_cliente(), i, 0);
            tabla.setValueAt(n.getCc_cliente(), i, 1);
            tabla.setValueAt(n.getCuenta_cliente(), i, 2);
            tabla.setValueAt(n.getNombre_cliente(), i, 3);
            tabla.setValueAt(n.getEmpresa_cliente(), i, 4);
            tabla.setValueAt(n.getNo_venta(), i, 5);
            tabla.setValueAt(n.getFecha_venta(), i, 6);
            tabla.setValueAt(n.getPropina_venta(), i, 7);
            tabla.setValueAt(n.getTotal_venta(), i, 8);
            tabla.setValueAt(n.getDescuento_venta(), i, 9);
            tabla.setValueAt(n.getExtra_venta(), i, 10);
            tabla.setValueAt(n.getTotal(), i, 11);
            tabla.setValueAt(n.getPago(), i, 12);
            tabla.setValueAt(n.getEmpleado(), i, 13);
            //consultar el valor de los servicios segun el codigo
            System.out.println("Consultando el servicio");
            try {
                lista_servicio = acceso_servicio.buscarCostoServicio(n.getCodigo_cliente());
                tabla.setValueAt(lista_servicio.get(0).getDescripcion_servicio(),i,14);
                tabla.setValueAt(lista_servicio.get(0).getPrecio_servicio(),i,15);
            }catch(Exception error){
                tabla.setValueAt("No tiene servicio",i,14);
                tabla.setValueAt("0.00",i,15);
            }
            i++;
        }
        
        tblOrdenes.setModel(tabla);
        tblOrdenes.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblOrdenes.getColumnModel().getColumn(1).setPreferredWidth(50);
        tblOrdenes.getColumnModel().getColumn(2).setPreferredWidth(50);
        tblOrdenes.getColumnModel().getColumn(3).setPreferredWidth(150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDetalle = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrdenes = new javax.swing.JTable();
        pnlBotones = new javax.swing.JPanel();
        btnMostrar = new javax.swing.JButton();
        txtFechaFinal = new javax.swing.JTextField();
        lblHasta = new javax.swing.JLabel();
        txtFechaInicial = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        lblText = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ventas Consolidado");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/historialVentas.png"))); // NOI18N

        pnlDetalle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblOrdenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrdenesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOrdenes);

        javax.swing.GroupLayout pnlDetalleLayout = new javax.swing.GroupLayout(pnlDetalle);
        pnlDetalle.setLayout(pnlDetalleLayout);
        pnlDetalleLayout.setHorizontalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDetalleLayout.setVerticalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlBotones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        lblHasta.setText("Fin");

        lblFecha.setText("Incio");

        lblText.setText("Codigo");

        txtCodigo.setText("0");

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblHasta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMostrar)
                .addContainerGap())
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrar)
                    .addComponent(txtFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHasta)
                    .addComponent(lblFecha)
                    .addComponent(txtFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblText)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDetalle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        mostrarOrdenes(txtFechaInicial.getText(), txtFechaFinal.getText(), txtCodigo.getText());
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void tblOrdenesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrdenesMouseClicked

    }//GEN-LAST:event_tblOrdenesMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHasta;
    private javax.swing.JLabel lblText;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlDetalle;
    private javax.swing.JTable tblOrdenes;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtFechaFinal;
    private javax.swing.JTextField txtFechaInicial;
    // End of variables declaration//GEN-END:variables
}
