/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package QuickMeal.Vistas;

import QuickMeal.Accesos.AccesoProveedor;
import QuickMeal.Accesos.Mensaje;
import QuickMeal.Objetos.ObjetoProveedor;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
//import QuickMeal.Accesos.

/**
 *
 * @author Megabytes Soluciones Integrales Guatemala
 */
public class CatalogoAdmonProveedores extends javax.swing.JInternalFrame {
    
    Mensaje Mensaje = new Mensaje();
    ObjetoProveedor proveedor = new ObjetoProveedor();
    AccesoProveedor nuevoProveedor = new AccesoProveedor();

    /**
     * Creates new form wdwIngresosProveedores
     */
    public CatalogoAdmonProveedores() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBotones = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        pnlEncabezado = new javax.swing.JPanel();
        lblIdProveedor = new javax.swing.JLabel();
        txtIdProveedor = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtDescripcionProveedor = new javax.swing.JTextField();
        lblNitPersona = new javax.swing.JLabel();
        txtNitProveedor = new javax.swing.JTextField();
        lblTelProveedor = new javax.swing.JLabel();
        txtTelProveedor = new javax.swing.JTextField();
        lblDirProveedor = new javax.swing.JLabel();
        txtDireccionProveedor = new javax.swing.JTextField();
        txtContactoProveedor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDiasCreditoProveedor = new javax.swing.JTextField();
        pnlDetalle = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProveedor = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Proveedores");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/proveedores.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(700, 600));
        setMinimumSize(new java.awt.Dimension(700, 600));
        setPreferredSize(new java.awt.Dimension(700, 600));

        pnlBotones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblBuscar.setText("Buscar");

        txtBuscar.setToolTipText("");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/buscar.png"))); // NOI18N
        btnBuscar.setActionCommand("buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/editar.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBuscar)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscar))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pnlEncabezado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblIdProveedor.setText("ID Proveedor");

        txtIdProveedor.setEditable(false);
        txtIdProveedor.setToolTipText("");

        lblNombre.setText("Descripcion");

        txtDescripcionProveedor.setToolTipText("");

        lblNitPersona.setText("NIT");

        txtNitProveedor.setToolTipText("");
        txtNitProveedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNitProveedorFocusLost(evt);
            }
        });

        lblTelProveedor.setText("TEL");

        txtTelProveedor.setToolTipText("");

        lblDirProveedor.setText("Direccion");

        txtDireccionProveedor.setToolTipText("");

        jLabel1.setText("Contacto");

        jLabel2.setText("Dias Credito");

        javax.swing.GroupLayout pnlEncabezadoLayout = new javax.swing.GroupLayout(pnlEncabezado);
        pnlEncabezado.setLayout(pnlEncabezadoLayout);
        pnlEncabezadoLayout.setHorizontalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdProveedor)
                    .addComponent(lblTelProveedor)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                        .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTelProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(txtIdProveedor))
                        .addGap(18, 18, 18)
                        .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDirProveedor)
                            .addComponent(lblNitPersona))
                        .addGap(11, 11, 11)
                        .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                                .addComponent(txtNitProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDescripcionProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                            .addComponent(txtDireccionProveedor)))
                    .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                        .addComponent(txtContactoProveedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDiasCreditoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlEncabezadoLayout.setVerticalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdProveedor)
                    .addComponent(txtIdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre)
                    .addComponent(txtDescripcionProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNitProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNitPersona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelProveedor)
                    .addComponent(txtTelProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDirProveedor)
                    .addComponent(txtDireccionProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContactoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtDiasCreditoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDetalle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProveedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProveedor);

        javax.swing.GroupLayout pnlDetalleLayout = new javax.swing.GroupLayout(pnlDetalle);
        pnlDetalle.setLayout(pnlDetalleLayout);
        pnlDetalleLayout.setHorizontalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDetalleLayout.setVerticalGroup(
            pnlDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarRegistro(){
        
        // Si se ingresan todos los datos del proveedor asigno valor a los objetos
        if(verificarDatosProveedor()){
            proveedor.setNit_proveedor(txtNitProveedor.getText());
            proveedor.setDescripcion_proveedor(txtDescripcionProveedor.getText());
            proveedor.setTelefono_proveedor(Integer.parseInt(txtTelProveedor.getText()));
            proveedor.setDireccion_proveedor(txtDireccionProveedor.getText());
            proveedor.setContacto_proveedor(txtContactoProveedor.getText());
        }
        
        try{
            nuevoProveedor.insertarProveedor(proveedor);
        }catch(Exception error){
            Mensaje.manipulacionExcepciones("critico", "Ocurrio un error al guardar los datos del proveedor " + error);
        }
        
    }
    
    private boolean verificarDatosProveedor(){
        boolean vDatosCorrectos = true;
        
        if(txtNitProveedor.getText().isEmpty()){
            Mensaje.manipulacionExcepciones("critico", "Ingrese el numero de NIT");
            vDatosCorrectos = false;
        }
        if (txtDescripcionProveedor.getText().isEmpty()) {
            Mensaje.manipulacionExcepciones("critico", "Ingrese la descripcion del proveedor");
            vDatosCorrectos = false;
        }
        if (txtTelProveedor.getText().isEmpty()) {
            Mensaje.manipulacionExcepciones("critico", "Ingrese el numero de Telefono");
            vDatosCorrectos = false;
        }
        if (txtDireccionProveedor.getText().isEmpty()) {
            Mensaje.manipulacionExcepciones("critico", "Ingrese la Direccion del proveedor");
            vDatosCorrectos = false;
        }
        if (txtContactoProveedor.getText().isEmpty()) {
            Mensaje.manipulacionExcepciones("critico", "Ingrese el contacto del proveedor");
            vDatosCorrectos = false;
        }
        
        return vDatosCorrectos;
    }
    
    private void limpiarCampos(){
        btnGuardar.setEnabled(true);
        txtIdProveedor.setText("");
        txtNitProveedor.setText("");
        txtDescripcionProveedor.setText("");
        txtDireccionProveedor.setText("");
        txtContactoProveedor.setText("");
        txtTelProveedor.setText("");
        txtDiasCreditoProveedor.setText("");
        txtBuscar.setText("");
    }
    
    private void actualizarRegistro(){
        proveedor.setId_proveedor(Integer.parseInt(txtIdProveedor.getText()));
        proveedor.setNit_proveedor(txtNitProveedor.getText());
        proveedor.setDescripcion_proveedor(txtDescripcionProveedor.getText());
        proveedor.setDireccion_proveedor(txtDireccionProveedor.getText());
        proveedor.setContacto_proveedor(txtContactoProveedor.getText());
        proveedor.setTelefono_proveedor(Integer.parseInt(txtTelProveedor.getText()));
        proveedor.setDias_credito_proveedor(Integer.parseInt(txtDiasCreditoProveedor.getText()));
        try{
            nuevoProveedor.actualizarProveedor(proveedor);
        }catch(Exception error){
            Mensaje.manipulacionExcepciones("critico", "Error al actualizar el proveedor " + error);
        }
    }
    
    private int obtenerIdProveedor(String pNit_proveedor){
        int vId_proveedor = 0;
        ArrayList<ObjetoProveedor> BuscarProveedor = new ArrayList();
        
        try{
            BuscarProveedor = nuevoProveedor.buscarProveedor(pNit_proveedor);
        }catch(Exception error){
            Mensaje.manipulacionExcepciones("critico", "Ocurrio un error al consultar el NIT del proveedor " + error);
        }
        
        if(BuscarProveedor.isEmpty()){
            Mensaje.manipulacionExcepciones("informacion", "Debe crear el proveedor en el sistema");
        }else{
            if(BuscarProveedor.size() > 1){
                System.out.println("EXISTEN " + BuscarProveedor.size() + " PROVEEDORES CON ESTE NUMERO DE NIT");
                Mensaje.manipulacionExcepciones("critico", "Este numero de Nit esta repetido");
            }else{
                vId_proveedor = BuscarProveedor.get(0).getId_proveedor();
            }
        }
        
        return vId_proveedor;
    }
    
    private void buscarEnRegistrosGuardados(){
        String busqueda = txtBuscar.getText();
        
        if(busqueda != null){
            DefaultTableModel tabla = new DefaultTableModel();
            
            ArrayList<ObjetoProveedor> listaProveedores = new ArrayList();
            
            int contadorFilas = 1;
            int cProveedor = 0;
            
            // Verificar algun erro al cargar la informacion de los proveedores
            try{
                listaProveedores = nuevoProveedor.seleccionarProveedor(busqueda);
                
                System.out.println("SE CONSULTARON LOS DATOS DE PROVEEDORES");
                
            }catch(Error error){
                Mensaje.manipulacionExcepciones("critico", "Ocurrio un error al consultar la informacion " + error);
            }
            
            // Mostrar la informacion de los proveedores en la tabla de la vista
            if(listaProveedores.isEmpty()){
                Mensaje.manipulacionExcepciones("critico", "No existe datos almacenados de los proveedores");
            }else{
                tabla.addColumn("NIT");
                tabla.addColumn("NOMBRE");
                tabla.addColumn("DIRECCION");
                tabla.addColumn("CONTACTO");
                tabla.addColumn("TELEFONO");
                tabla.addColumn("DIAS CREDITO");
                
                for(ObjetoProveedor xProveedor : listaProveedores){
                    
                    tabla.setRowCount(contadorFilas);
                    
                    tabla.setValueAt(xProveedor.getNit_proveedor(), cProveedor, 0);
                    tabla.setValueAt(xProveedor.getDescripcion_proveedor(), cProveedor, 1);
                    tabla.setValueAt(xProveedor.getDireccion_proveedor(), cProveedor, 2);
                    tabla.setValueAt(xProveedor.getContacto_proveedor(), cProveedor, 3);
                    tabla.setValueAt(xProveedor.getTelefono_proveedor(), cProveedor, 4);
                    tabla.setValueAt(xProveedor.getDias_credito_proveedor(), cProveedor, 5);
                    
                    System.out.println("Se encontro el registro " + xProveedor.getDescripcion_proveedor());
                    cProveedor++;
                    contadorFilas++;
                    
                }
                
                tblProveedor.setModel(tabla);    
            }
            
        }else{
            mostrarRegistrosGuardados();
        }
        
    }
    
    public void mostrarRegistrosGuardados(){
        DefaultTableModel tabla = new DefaultTableModel();
        
         ArrayList<ObjetoProveedor> listaProveedores = new ArrayList();
         
         try{
             listaProveedores = nuevoProveedor.retornaProveedores();
             
         }catch(Exception error){
             Mensaje.manipulacionExcepciones("critico", "Error en busqueda " + error);
         }
         
         if(listaProveedores.isEmpty()){
             Mensaje.manipulacionExcepciones("critico", "No existen datos almacenados de proveedores");
         }else{
             tabla.addColumn("NIT");
                tabla.addColumn("NOMBRE");
                tabla.addColumn("DIRECCION");
                tabla.addColumn("CONTACTO");
                tabla.addColumn("TELEFONO");
                tabla.addColumn("DIAS CREDITO");
                
                tabla.setRowCount(listaProveedores.size());
                int cProveedor = 0;
                
                for(ObjetoProveedor xProveedor : listaProveedores){
                    
                    tabla.setValueAt(xProveedor.getNit_proveedor(), cProveedor, 0);
                    tabla.setValueAt(xProveedor.getDescripcion_proveedor(), cProveedor, 1);
                    tabla.setValueAt(xProveedor.getDireccion_proveedor(), cProveedor, 2);
                    tabla.setValueAt(xProveedor.getContacto_proveedor(), cProveedor, 3);
                    tabla.setValueAt(xProveedor.getTelefono_proveedor(), cProveedor, 4);
                    tabla.setValueAt(xProveedor.getDias_credito_proveedor(), cProveedor, 5);
                    
                    System.out.println("Se encontro el registro " + xProveedor.getDescripcion_proveedor());
                    
                    cProveedor++;
                }
         }
         tblProveedor.setModel(tabla);
    }
    
     private void buscarProveedor() {

        boolean proveedor_encontrado = false;

        ArrayList<ObjetoProveedor> BuscarProveedor = new ArrayList();

        try {
            BuscarProveedor = nuevoProveedor.buscarProveedor(txtNitProveedor.getText());
        } catch (Exception error) {
            Mensaje.manipulacionExcepciones("critico", "Ocurrio un erro al buscar informacion sobre este proveedor " + error);
        }

        if (BuscarProveedor.isEmpty()) {
            proveedor_encontrado = false;
        } else {
            if(BuscarProveedor.size() > 1){
                System.out.println("EXISTEN " + BuscarProveedor.size() + " PROVEEDORES CON ESTE NUMERO DE NIT");
                Mensaje.manipulacionExcepciones("critico", "Este codigo esta repetido");
            }else{
                proveedor_encontrado = true;
                txtDescripcionProveedor.setText(BuscarProveedor.get(0).getDescripcion_proveedor());
                txtTelProveedor.setText(String.valueOf(BuscarProveedor.get(0).getTelefono_proveedor()));
                txtDireccionProveedor.setText(BuscarProveedor.get(0).getDireccion_proveedor());
                txtContactoProveedor.setText(BuscarProveedor.get(0).getContacto_proveedor());
                txtDiasCreditoProveedor.setText(String.valueOf(BuscarProveedor.get(0).getDias_credito_proveedor()));
            }
            
        }
    }
     
    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarEnRegistrosGuardados();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarRegistro();
        mostrarRegistrosGuardados();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if(txtNitProveedor.getText().isEmpty()){
            Mensaje.manipulacionExcepciones("informacion", "Debe seleccionar el registro a modificar");
        }else{
            actualizarRegistro();
            mostrarRegistrosGuardados();
        }
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        Mensaje.manipulacionExcepciones("interrogante", "¿Esta seguro que desea salir?");
        if (Mensaje.valor == 0) {
            dispose();
        }

    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtNitProveedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNitProveedorFocusLost
        buscarProveedor();
    }//GEN-LAST:event_txtNitProveedorFocusLost

    private void tblProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProveedorMouseClicked
        btnGuardar.setEnabled(false);
        txtNitProveedor.setText(String.valueOf(tblProveedor.getValueAt(tblProveedor.getSelectedRow(), 0)));
        txtDescripcionProveedor.setText(String.valueOf(tblProveedor.getValueAt(tblProveedor.getSelectedRow(), 1)));
        txtDireccionProveedor.setText(String.valueOf(tblProveedor.getValueAt(tblProveedor.getSelectedRow(), 2)));
        txtContactoProveedor.setText(String.valueOf(tblProveedor.getValueAt(tblProveedor.getSelectedRow(), 3)));
        txtTelProveedor.setText(String.valueOf(tblProveedor.getValueAt(tblProveedor.getSelectedRow(),4)));
        txtDiasCreditoProveedor.setText(String.valueOf(tblProveedor.getValueAt(tblProveedor.getSelectedRow(),5)));
        txtIdProveedor.setText(String.valueOf(obtenerIdProveedor(txtNitProveedor.getText())));
    }//GEN-LAST:event_tblProveedorMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblDirProveedor;
    private javax.swing.JLabel lblIdProveedor;
    private javax.swing.JLabel lblNitPersona;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelProveedor;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlDetalle;
    private javax.swing.JPanel pnlEncabezado;
    private javax.swing.JTable tblProveedor;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtContactoProveedor;
    private javax.swing.JTextField txtDescripcionProveedor;
    private javax.swing.JTextField txtDiasCreditoProveedor;
    private javax.swing.JTextField txtDireccionProveedor;
    private javax.swing.JTextField txtIdProveedor;
    private javax.swing.JTextField txtNitProveedor;
    private javax.swing.JTextField txtTelProveedor;
    // End of variables declaration//GEN-END:variables
}
