/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package QuickMeal.Vistas;

import QuickMeal.Accesos.AccesoLoggin;
import QuickMeal.Accesos.Mensaje;
import QuickMeal.Objetos.ObjetoLoggin;
import java.util.ArrayList;

/**
 *
 * @author Derwin
 */
public class IngresoDeUsuario extends javax.swing.JInternalFrame {

    Mensaje mensaje = new Mensaje();
    
    /**
     * Creates new form IngresoDeUsuario
     */
    public IngresoDeUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUsuario = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        lblClave = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtIdEstacion = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setTitle("Ingreso de Usuario");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/user.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(300, 250));
        setMinimumSize(new java.awt.Dimension(300, 250));
        setPreferredSize(new java.awt.Dimension(300, 250));

        pnlUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblUsuario.setText("Usuario");

        txtUsuario.setToolTipText("Ingrese el Tipo de Usuario");

        lblClave.setText("Contraseña");

        jLabel1.setText("Estacion");

        javax.swing.GroupLayout pnlUsuarioLayout = new javax.swing.GroupLayout(pnlUsuario);
        pnlUsuario.setLayout(pnlUsuarioLayout);
        pnlUsuarioLayout.setHorizontalGroup(
            pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtContrasenia)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addGroup(pnlUsuarioLayout.createSequentialGroup()
                        .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuario)
                            .addComponent(lblClave)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtIdEstacion))
                .addContainerGap())
        );
        pnlUsuarioLayout.setVerticalGroup(
            pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuarioLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblUsuario)
                .addGap(1, 1, 1)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtIdEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/aceptar.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 58, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void comprobarUsuario() {
        String tipo = "";
        
        AccesoLoggin loggin = new AccesoLoggin();
        ArrayList<ObjetoLoggin> usuario = new ArrayList();

        try{
            usuario = loggin.ingresoUsuario(txtUsuario.getText(), txtContrasenia.getText(), Integer.parseInt(txtIdEstacion.getText()));
        }catch(Exception error){
            mensaje.manipulacionExcepciones("critico", "Ocurrio un error al consultar el usuario");
        }
        
        if(usuario.isEmpty()){
            mensaje.manipulacionExcepciones("advertencia", "Este usuario no existe");
        } else {
            for(ObjetoLoggin n:usuario){
                tipo = n.getTipo_usuario();
                QuickMeal.usuarioLogueado(n.getId_estacion(), n.getDescripcion_estacion(), n.getId_usuario(), n.getNombre_usuario());
            }
        }
        
        //PIDIERON QUE SE ELIMINARAN ESTOS REPORTES
        //SOLO SE OCULTARON PARA NO PODER VERLOS
        QuickMeal.menuReportesHisComprasCC.setVisible(false);
        QuickMeal.menuReportesHisComprasCC1.setVisible(false);
        QuickMeal.menuResumenPropinas.setVisible(false);
        QuickMeal.menuCobroAreaExcel.setVisible(true);
        QuickMeal.menuCobroCliente.setVisible(false);
        QuickMeal.menuReportesPlanilla.setVisible(false);
        QuickMeal.menuCobroAreaExcel.setVisible(false);
        
        //VALIDAR LOS PERMISOS POR TIPO DE USUARIO
        //USUARIO ADMINISTRADOR
        
        if(tipo.equals("Administrador")) {
            QuickMeal.menu.setVisible(true);
            this.dispose();
        }
        
        if(tipo.equals("Cajero")){
            QuickMeal.menu.setVisible(true);
            QuickMeal.menuMovimiento.setVisible(true);
            QuickMeal.menuEditarOrdenes.setVisible(false);
            QuickMeal.menuCompraDeProductos.setVisible(false);
            QuickMeal.menuVentaDeProductos.setVisible(true);
            QuickMeal.menuOrdenesActivas.setVisible(true);
            QuickMeal.menuPantallaCocina.setVisible(true);
            QuickMeal.menuCatalogo.setVisible(false);
            QuickMeal.menuReportes.setVisible(true);
            QuickMeal.menuBaseDeDatos.setVisible(false);
            QuickMeal.menuSistema.setVisible(false);
            QuickMeal.menuAyuda.setVisible(true);
            QuickMeal.menuProveedores.setVisible(false);
            QuickMeal.menuEmpleados.setVisible(false);
            QuickMeal.menuProductos.setVisible(false);
            QuickMeal.menuLotes.setVisible(false);
            QuickMeal.menuCategoria.setVisible(false);
            QuickMeal.menuIngredientes.setVisible(false);
            QuickMeal.menuMiselaneos.setVisible(false);
            QuickMeal.menuBaseDeDatos.setVisible(true);
            QuickMeal.menuExportarCatalogoDeProductos.setVisible(false);
            QuickMeal.menuImportarCatalogoDeProductos.setVisible(false);
            QuickMeal.menuHistorialOrdenes.setVisible(true);
            this.dispose();
        }
        
        if(tipo.equals("Chef")){
            QuickMeal.menu.setVisible(true);
            QuickMeal.menuMovimiento.setVisible(true);
            QuickMeal.menuCompraDeProductos.setVisible(false);
            QuickMeal.menuVentaDeProductos.setVisible(false);
            QuickMeal.menuOrdenesActivas.setVisible(false);
            QuickMeal.menuPantallaCocina.setVisible(true);
            QuickMeal.menuCatalogo.setVisible(false);
            QuickMeal.menuReportes.setVisible(false);
            QuickMeal.menuBaseDeDatos.setVisible(false);
            QuickMeal.menuSistema.setVisible(false);
            QuickMeal.menuAyuda.setVisible(true);
            this.dispose();
        }
    }

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        comprobarUsuario();
    }//GEN-LAST:event_btnAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlUsuario;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtIdEstacion;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
