/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package QuickMeal.Vistas;

import QuickMeal.Accesos.AccesoOrden;
import QuickMeal.Librerias.ImagenCocina;
import QuickMeal.Objetos.ObjetoOrden;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Megabyte Soluciones Integrales Guatemala
 */

public class MovimientoPantallaCocina extends javax.swing.JInternalFrame {

    /**
     * Creates new form MovimientoVentaDeProductos
     */
    public MovimientoPantallaCocina() {
        initComponents();
        
        //COLOCAR FONOD EN LA PANTALLA PARA LA COCINA
        try{
            pnlOrdenes.setBorder(new ImagenCocina());
        } catch (IOException e){
           Logger.getLogger(MovimientoPantallaCocina.class.getName()).log(Level.SEVERE, null, e);
        }
        
        //VISUALIZAR TODAS LAS ORDENES ACTIVAS
        hilo p = new hilo("ordenes");
        p.start();
    }
    
    private void limpiarPantalla(){
        pnlOrdenes.removeAll();
        pnlOrdenes.updateUI();
    }
    
    private void mostrarOrdenesActivas() {
        
        this.toBack();
        
        AccesoOrden orden = new AccesoOrden();
        ArrayList<ObjetoOrden> lista = new ArrayList();
        
        int x = 0;
        int y = 0;

        try {
            lista = orden.listar("P");
        } catch (Exception e) {
        }
        
        if (lista.isEmpty()){
            
        } else {
            for (ObjetoOrden n:lista){
                Orden nueva_orden = new Orden();
                pnlOrdenes.add(nueva_orden);
                nueva_orden.setVisible(true);
                nueva_orden.ordenNumero(String.valueOf(n.getId_orden()));
                nueva_orden.setLocation(x * 220, y * 240);
                x++;
                if (x == 7) {
                    x=0;
                    y++;
                }
            }
        }
    }
    
    private class hilo implements Runnable {
        private Thread hilo;
        private String nombre;
        
        public hilo(String nombre){
            this.nombre = nombre;
            hilo = new Thread(this, "Hilo");
        }
        
        public void start(){
            hilo.start();
        }
        
        @Override
        public void run() {
            try {
                while(true){
                    if(nombre.equals("ordenes")){
                        pnlOrdenes.removeAll();
                        limpiarPantalla();
                        mostrarOrdenesActivas();
                        Thread.sleep(60000);
                    }
                }
            } catch(InterruptedException e) {
                System.out.println("Error en ejecucion hilo");
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlOrdenes = new javax.swing.JDesktopPane();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Pantalla Cocina");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/pantalla.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(4500, 3250));
        setMinimumSize(new java.awt.Dimension(900, 700));
        setPreferredSize(new java.awt.Dimension(900, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOrdenes, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOrdenes, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane pnlOrdenes;
    // End of variables declaration//GEN-END:variables
}
