/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package QuickMeal.Vistas;

import QuickMeal.Accesos.AccesoDetalleVenta;
import QuickMeal.Accesos.AccesoOrden;
import QuickMeal.Accesos.Conexion;
import QuickMeal.Accesos.Mensaje;
import QuickMeal.Objetos.ObjetoItem;
import java.net.URL;
import java.util.ArrayList;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Megabyte Soluciones Integrales Guatemala
 */
public class Orden extends javax.swing.JInternalFrame {

    private AccesoOrden orden = new AccesoOrden();
    private AccesoDetalleVenta detalle_venta = new AccesoDetalleVenta();
    private ArrayList<ObjetoItem> item = new ArrayList();
    
    /**
     * Creates new form wdwAyudaAcercaDeInventario
     */
    public Orden(){
        initComponents();
    }
    
    public void ordenNumero(String numero){
        txtIdOrden.setText(numero);
        item = detalle_venta.buscarDetalleVenta(numero);
        //MOSTRAR EL DETALLE DE LA VENTA
        String descripcion = "";
        for(ObjetoItem n:item){
            descripcion = descripcion + n.getDescripcion_item().toUpperCase() + "\n";
        }
        txtDetalle.setText(descripcion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdOrden = new javax.swing.JLabel();
        btnDespacharOrden = new javax.swing.JButton();
        btnVisualizar = new javax.swing.JButton();
        btnCancelarOrden = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetalle = new javax.swing.JTextArea();

        setTitle("Orden");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/orden.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(200, 250));
        setMinimumSize(new java.awt.Dimension(200, 250));
        setPreferredSize(new java.awt.Dimension(200, 250));

        txtIdOrden.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtIdOrden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtIdOrden.setText("id_orden");

        btnDespacharOrden.setBackground(new java.awt.Color(0, 255, 102));
        btnDespacharOrden.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnDespacharOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/aceptar.png"))); // NOI18N
        btnDespacharOrden.setMaximumSize(new java.awt.Dimension(50, 50));
        btnDespacharOrden.setMinimumSize(new java.awt.Dimension(50, 50));
        btnDespacharOrden.setPreferredSize(new java.awt.Dimension(50, 50));
        btnDespacharOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDespacharOrdenActionPerformed(evt);
            }
        });

        btnVisualizar.setBackground(new java.awt.Color(255, 255, 0));
        btnVisualizar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/visualizar.png"))); // NOI18N
        btnVisualizar.setMaximumSize(new java.awt.Dimension(50, 50));
        btnVisualizar.setMinimumSize(new java.awt.Dimension(50, 50));
        btnVisualizar.setPreferredSize(new java.awt.Dimension(50, 50));
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });

        btnCancelarOrden.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelarOrden.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCancelarOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/cancelar.png"))); // NOI18N
        btnCancelarOrden.setMaximumSize(new java.awt.Dimension(50, 50));
        btnCancelarOrden.setMinimumSize(new java.awt.Dimension(50, 50));
        btnCancelarOrden.setPreferredSize(new java.awt.Dimension(50, 50));
        btnCancelarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarOrdenActionPerformed(evt);
            }
        });

        txtDetalle.setBackground(new java.awt.Color(240, 240, 240));
        txtDetalle.setColumns(20);
        txtDetalle.setEditable(false);
        txtDetalle.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        txtDetalle.setLineWrap(true);
        txtDetalle.setRows(5);
        txtDetalle.setAutoscrolls(false);
        jScrollPane1.setViewportView(txtDetalle);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDespacharOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(btnCancelarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtIdOrden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtIdOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDespacharOrden, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVisualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarOrden, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDespacharOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDespacharOrdenActionPerformed
        //COLOCAR EL ESTADO DE LOS ITEMS ANTERIORES COMO DESPACHADOS
        detalle_venta.cambiaEstadoItemVenta(Integer.parseInt(txtIdOrden.getText()));
        orden.despacharOrden(txtIdOrden.getText());
        dispose();
    }//GEN-LAST:event_btnDespacharOrdenActionPerformed

    private void btnCancelarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarOrdenActionPerformed
        // TODO add your handling code here:
       orden.cancelarOrden(txtIdOrden.getText());
       dispose();
    }//GEN-LAST:event_btnCancelarOrdenActionPerformed

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        Mensaje mensaje = new Mensaje();
        try{
            Conexion acceso = new Conexion();
            URL url_reporte = this.getClass().getResource("/QuickMeal/Reportes/nota.jasper");
            JasperReport reporte = (JasperReport) JRLoader.loadObject(url_reporte);
            HashMap parametro = new HashMap();
            parametro.put("P_ID_ORDEN", Integer.parseInt(txtIdOrden.getText()));
            parametro.put("P_ESTADO_ORDEN", "P");
            parametro.put("P_ESTADO_DETALLE", "P");
            JasperPrint pantalla = JasperFillManager.fillReport(reporte, parametro, acceso.conectar());
            JasperViewer visualizador = new JasperViewer(pantalla, false);
            visualizador.show();
        }catch(Exception error){
            mensaje.manipulacionExcepciones("critico", "No se puede generar el reporte");
        }
    }//GEN-LAST:event_btnVisualizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarOrden;
    private javax.swing.JButton btnDespacharOrden;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDetalle;
    private javax.swing.JLabel txtIdOrden;
    // End of variables declaration//GEN-END:variables
}
