/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package QuickMeal.Vistas;

import QuickMeal.Accesos.AccesoProducto;
import QuickMeal.Accesos.Conexion;
import QuickMeal.Librerias.ImagenFondo;
import java.awt.Image;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.io.IOException;
import java.net.URL;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Megabytes Soluciones Integrales Guatemala
 */
public class QuickMeal extends javax.swing.JFrame {

    /**
     * Creates new form QuickMeal
     */
    public QuickMeal() {
        initComponents();
        try {
            pnlPrincipal.setBorder(new ImagenFondo());
        } catch (IOException ex) {
            Logger.getLogger(QuickMeal.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        menu.setVisible(false);
        
        IngresoDeUsuario Ingreso = new IngresoDeUsuario();
        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        
        int x  = (ancho / 2) - (Ingreso.getWidth() / 2);
        int y  = (alto / 2) - Ingreso.getHeight();
        
        if(Ingreso.isShowing()){
            Ingreso.setLocation(x, y);
        } else {
            pnlPrincipal.add(Ingreso);
            Ingreso.setLocation(x, y);
            Ingreso.setVisible(true);
            Ingreso.toFront();
        }
        
        verificarProductos();
        
    }
    
    @Override
    public Image getIconImage(){
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("QuickMeal/Imagenes/logotipo.png"));
        return icono;
    }
    
    private void verificarProductos(){
        try {
            //verificar si hay productos al minimo
            AccesoProducto acceso_producto = new AccesoProducto();
            if (acceso_producto.buscarProductosEnMinimo().equals("SI")) {
                txtMensaje.setText("Verifique los productos al minimo");
                QuickMeal.btnProductosMinimo.setEnabled(true);
            }
        } catch (Exception e) {
            System.out.println("Error al verificar productos al iniciar el programa");
        }
    }
    
    public static void usuarioLogueado(int id_estacion, String descripcion_estacion, int codigo_usuario, String nombre_usuario){
        txtIdEstacion.setText(String.valueOf(id_estacion));
        txtDescripcionEstacion.setText(descripcion_estacion);
        txtCodigoUsuario.setText(String.valueOf(codigo_usuario));
        txtNombreUsuario.setText(nombre_usuario);
    }
    
    public static int getIdEstacion(){
        return Integer.parseInt(txtIdEstacion.getText());
    }
    
    public static int getIdUsuario(){
        return Integer.parseInt(txtCodigoUsuario.getText());
    }
    
    public static String getNombreUsuario(){
        return txtNombreUsuario.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        pnlPrincipal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        txtIdEstacion = new javax.swing.JLabel();
        txtDescripcionEstacion = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodigoUsuario = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JLabel();
        txtMensaje = new javax.swing.JLabel();
        btnProductosMinimo = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        menuMovimiento = new javax.swing.JMenu();
        menuCompraDeProductos = new javax.swing.JMenuItem();
        menuAjusteProducto = new javax.swing.JMenuItem();
        menuVentaDeProductos = new javax.swing.JMenuItem();
        menuOrdenesActivas = new javax.swing.JMenuItem();
        menuEditarOrdenes = new javax.swing.JMenuItem();
        menuPantallaCocina = new javax.swing.JMenuItem();
        menuCatalogo = new javax.swing.JMenu();
        menuAdministracion = new javax.swing.JMenu();
        menuClientes = new javax.swing.JMenuItem();
        menuProveedores = new javax.swing.JMenuItem();
        menuEmpleados = new javax.swing.JMenuItem();
        menuProductos = new javax.swing.JMenuItem();
        menuLotes = new javax.swing.JMenuItem();
        menuRestaurante = new javax.swing.JMenu();
        menuCategoria = new javax.swing.JMenuItem();
        menuItem = new javax.swing.JMenuItem();
        menuIngredientes = new javax.swing.JMenuItem();
        menuMiselaneos = new javax.swing.JMenu();
        menuServicios = new javax.swing.JMenuItem();
        menuSuscripciones = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        menuReportesInventarioDeProductos = new javax.swing.JMenuItem();
        menuReportesHisComprasClienteDetallado1 = new javax.swing.JMenuItem();
        menuReportesHisComprasClienteDetallado = new javax.swing.JMenuItem();
        menuReportesHisComprasClienteDetallado2 = new javax.swing.JMenuItem();
        menuReportesHIsComprasClienteConsolidado = new javax.swing.JMenuItem();
        menuReportesIngredientesPorFecha = new javax.swing.JMenuItem();
        menuReportesProductosMasVendidos = new javax.swing.JMenuItem();
        menuReportesPlanilla = new javax.swing.JMenuItem();
        menuReportesHisComprasCC = new javax.swing.JMenuItem();
        menuReportesHisComprasCC1 = new javax.swing.JMenuItem();
        menuReportesReOrden = new javax.swing.JMenuItem();
        menuReportesCambioPrecio = new javax.swing.JMenuItem();
        menuReportesCierreDiarioCaja = new javax.swing.JMenuItem();
        menuBaseDeDatos = new javax.swing.JMenu();
        menuExportarCatalogoDeProductos = new javax.swing.JMenuItem();
        menuImportarCatalogoDeProductos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuHistorialCompraProductos = new javax.swing.JMenuItem();
        menuHistorialOrdenes = new javax.swing.JMenuItem();
        menuCobroCliente = new javax.swing.JMenuItem();
        menuCobroAreaExcel = new javax.swing.JMenuItem();
        menuResumenPropinas = new javax.swing.JMenuItem();
        menuHistorialCompras = new javax.swing.JMenuItem();
        menuSistema = new javax.swing.JMenu();
        menuUsuarios = new javax.swing.JMenuItem();
        menuParametros = new javax.swing.JMenuItem();
        menuSistemaEstaciones = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        menuManualDeUsuario = new javax.swing.JMenuItem();
        menuAcercaDe = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QuickMeal");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setName("LaEconomicaInventario"); // NOI18N

        jLabel1.setText("Estacion:");

        txtIdEstacion.setText("ID");

        txtDescripcionEstacion.setText("Decripcion");

        jLabel4.setText("Usuario:");

        txtCodigoUsuario.setText("Codigo");

        txtNombreUsuario.setText("Nombre");

        txtMensaje.setText("Mensaje");

        btnProductosMinimo.setText("Productos al Minimo");
        btnProductosMinimo.setEnabled(false);
        btnProductosMinimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosMinimoActionPerformed(evt);
            }
        });

        menuMovimiento.setText("Movimiento");

        menuCompraDeProductos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menuCompraDeProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/compras.png"))); // NOI18N
        menuCompraDeProductos.setText("Compras de Productos");
        menuCompraDeProductos.setToolTipText("");
        menuCompraDeProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCompraDeProductosActionPerformed(evt);
            }
        });
        menuMovimiento.add(menuCompraDeProductos);

        menuAjusteProducto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menuAjusteProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/balance.png"))); // NOI18N
        menuAjusteProducto.setText("Ajuste de Productos");
        menuAjusteProducto.setToolTipText("");
        menuAjusteProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAjusteProductoActionPerformed(evt);
            }
        });
        menuMovimiento.add(menuAjusteProducto);

        menuVentaDeProductos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        menuVentaDeProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/ventas.png"))); // NOI18N
        menuVentaDeProductos.setText("Venta de Productos");
        menuVentaDeProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVentaDeProductosActionPerformed(evt);
            }
        });
        menuMovimiento.add(menuVentaDeProductos);

        menuOrdenesActivas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        menuOrdenesActivas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/orden.png"))); // NOI18N
        menuOrdenesActivas.setText("Ordenes Activas");
        menuOrdenesActivas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOrdenesActivasActionPerformed(evt);
            }
        });
        menuMovimiento.add(menuOrdenesActivas);

        menuEditarOrdenes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        menuEditarOrdenes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/editar.png"))); // NOI18N
        menuEditarOrdenes.setText("Editar Ordenes");
        menuEditarOrdenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarOrdenesActionPerformed(evt);
            }
        });
        menuMovimiento.add(menuEditarOrdenes);

        menuPantallaCocina.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        menuPantallaCocina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/pantalla.png"))); // NOI18N
        menuPantallaCocina.setText("Pantalla Cocina");
        menuPantallaCocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPantallaCocinaActionPerformed(evt);
            }
        });
        menuMovimiento.add(menuPantallaCocina);

        menu.add(menuMovimiento);

        menuCatalogo.setText("Catalogo");

        menuAdministracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/salir.png"))); // NOI18N
        menuAdministracion.setText("Administracion");

        menuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/clientes.png"))); // NOI18N
        menuClientes.setText("Clientes");
        menuClientes.setToolTipText("Ingreso de Clientes");
        menuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesActionPerformed(evt);
            }
        });
        menuAdministracion.add(menuClientes);

        menuProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/proveedores.png"))); // NOI18N
        menuProveedores.setText("Proveedores");
        menuProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProveedoresActionPerformed(evt);
            }
        });
        menuAdministracion.add(menuProveedores);

        menuEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/empleado.png"))); // NOI18N
        menuEmpleados.setText("Empleados");
        menuEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmpleadosActionPerformed(evt);
            }
        });
        menuAdministracion.add(menuEmpleados);

        menuProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/producto.png"))); // NOI18N
        menuProductos.setText("Productos");
        menuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosActionPerformed(evt);
            }
        });
        menuAdministracion.add(menuProductos);

        menuLotes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/lote.png"))); // NOI18N
        menuLotes.setText("Control de Lotes");
        menuLotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLotesActionPerformed(evt);
            }
        });
        menuAdministracion.add(menuLotes);

        menuCatalogo.add(menuAdministracion);

        menuRestaurante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/restaurante.png"))); // NOI18N
        menuRestaurante.setText("Restaurante");

        menuCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/categoria.png"))); // NOI18N
        menuCategoria.setText("Categorias");
        menuCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCategoriaActionPerformed(evt);
            }
        });
        menuRestaurante.add(menuCategoria);

        menuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/item.png"))); // NOI18N
        menuItem.setText("Items");
        menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemActionPerformed(evt);
            }
        });
        menuRestaurante.add(menuItem);

        menuIngredientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/ingrediente.png"))); // NOI18N
        menuIngredientes.setText("Ingredientes");
        menuIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIngredientesActionPerformed(evt);
            }
        });
        menuRestaurante.add(menuIngredientes);

        menuCatalogo.add(menuRestaurante);

        menuMiselaneos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/micelaneo.png"))); // NOI18N
        menuMiselaneos.setText("Miselaneos");

        menuServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/servicio.png"))); // NOI18N
        menuServicios.setText("Servicios");
        menuServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuServiciosActionPerformed(evt);
            }
        });
        menuMiselaneos.add(menuServicios);

        menuSuscripciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/suscripcion.png"))); // NOI18N
        menuSuscripciones.setText("Suscripciones");
        menuSuscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSuscripcionesActionPerformed(evt);
            }
        });
        menuMiselaneos.add(menuSuscripciones);

        menuCatalogo.add(menuMiselaneos);

        menu.add(menuCatalogo);

        menuReportes.setText("Reportes");

        menuReportesInventarioDeProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/reporte.png"))); // NOI18N
        menuReportesInventarioDeProductos.setText("Inventario de Productos");
        menuReportesInventarioDeProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesInventarioDeProductosActionPerformed(evt);
            }
        });
        menuReportes.add(menuReportesInventarioDeProductos);

        menuReportesHisComprasClienteDetallado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/reporte.png"))); // NOI18N
        menuReportesHisComprasClienteDetallado1.setText("Historial Compras por Fecha");
        menuReportesHisComprasClienteDetallado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesHisComprasClienteDetallado1ActionPerformed(evt);
            }
        });
        menuReportes.add(menuReportesHisComprasClienteDetallado1);

        menuReportesHisComprasClienteDetallado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/reporte.png"))); // NOI18N
        menuReportesHisComprasClienteDetallado.setText("Ventas por Cliente Detallado");
        menuReportesHisComprasClienteDetallado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesHisComprasClienteDetalladoActionPerformed(evt);
            }
        });
        menuReportes.add(menuReportesHisComprasClienteDetallado);

        menuReportesHisComprasClienteDetallado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/reporte.png"))); // NOI18N
        menuReportesHisComprasClienteDetallado2.setText("Ventas por Cliente Consolidado");
        menuReportesHisComprasClienteDetallado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesHisComprasClienteDetallado2ActionPerformed(evt);
            }
        });
        menuReportes.add(menuReportesHisComprasClienteDetallado2);

        menuReportesHIsComprasClienteConsolidado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/reporte.png"))); // NOI18N
        menuReportesHIsComprasClienteConsolidado.setText("Ventas por Turno");
        menuReportesHIsComprasClienteConsolidado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesHIsComprasClienteConsolidadoActionPerformed(evt);
            }
        });
        menuReportes.add(menuReportesHIsComprasClienteConsolidado);

        menuReportesIngredientesPorFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/reporte.png"))); // NOI18N
        menuReportesIngredientesPorFecha.setText("Ingredientes Utilizados por Fecha");
        menuReportesIngredientesPorFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesIngredientesPorFechaActionPerformed(evt);
            }
        });
        menuReportes.add(menuReportesIngredientesPorFecha);

        menuReportesProductosMasVendidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/reporte.png"))); // NOI18N
        menuReportesProductosMasVendidos.setText("Productos Mas Vendidos");
        menuReportesProductosMasVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesProductosMasVendidosActionPerformed(evt);
            }
        });
        menuReportes.add(menuReportesProductosMasVendidos);

        menuReportesPlanilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/reporte.png"))); // NOI18N
        menuReportesPlanilla.setText("Planilla de Empleados");
        menuReportesPlanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesPlanillaActionPerformed(evt);
            }
        });
        menuReportes.add(menuReportesPlanilla);

        menuReportesHisComprasCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/reporte.png"))); // NOI18N
        menuReportesHisComprasCC.setText("Compras por Centro de Costo");
        menuReportesHisComprasCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesHisComprasCCActionPerformed(evt);
            }
        });
        menuReportes.add(menuReportesHisComprasCC);

        menuReportesHisComprasCC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/reporte.png"))); // NOI18N
        menuReportesHisComprasCC1.setText("Compras al Credito Clientes");
        menuReportesHisComprasCC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesHisComprasCC1ActionPerformed(evt);
            }
        });
        menuReportes.add(menuReportesHisComprasCC1);

        menuReportesReOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/reporte.png"))); // NOI18N
        menuReportesReOrden.setText("Punto de Re-Orden");
        menuReportesReOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesReOrdenActionPerformed(evt);
            }
        });
        menuReportes.add(menuReportesReOrden);

        menuReportesCambioPrecio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/reporte.png"))); // NOI18N
        menuReportesCambioPrecio.setText("Variacion Precio de Compra");
        menuReportesCambioPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesCambioPrecioActionPerformed(evt);
            }
        });
        menuReportes.add(menuReportesCambioPrecio);

        menuReportesCierreDiarioCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/reporte.png"))); // NOI18N
        menuReportesCierreDiarioCaja.setText("Cierre Diario Caja");
        menuReportesCierreDiarioCaja.setActionCommand("");
        menuReportesCierreDiarioCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportesCierreDiarioCajaActionPerformed(evt);
            }
        });
        menuReportes.add(menuReportesCierreDiarioCaja);

        menu.add(menuReportes);

        menuBaseDeDatos.setText("Base de Datos");

        menuExportarCatalogoDeProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/exportar.png"))); // NOI18N
        menuExportarCatalogoDeProductos.setText("Exportar Catalogo de Productos");
        menuExportarCatalogoDeProductos.setToolTipText("Exporta el catalo de productos a Excel");
        menuExportarCatalogoDeProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExportarCatalogoDeProductosActionPerformed(evt);
            }
        });
        menuBaseDeDatos.add(menuExportarCatalogoDeProductos);

        menuImportarCatalogoDeProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/importar.png"))); // NOI18N
        menuImportarCatalogoDeProductos.setText("Importar Catalogo de Productos");
        menuImportarCatalogoDeProductos.setToolTipText("Importar el catalogo de productos");
        menuImportarCatalogoDeProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuImportarCatalogoDeProductosActionPerformed(evt);
            }
        });
        menuBaseDeDatos.add(menuImportarCatalogoDeProductos);
        menuBaseDeDatos.add(jSeparator1);

        menuHistorialCompraProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/historialVentas.png"))); // NOI18N
        menuHistorialCompraProductos.setText("Consultar Compra");
        menuHistorialCompraProductos.setToolTipText("");
        menuHistorialCompraProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHistorialCompraProductosActionPerformed(evt);
            }
        });
        menuBaseDeDatos.add(menuHistorialCompraProductos);

        menuHistorialOrdenes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/historialVentas.png"))); // NOI18N
        menuHistorialOrdenes.setText("Historial de Ordenes Ingresadas");
        menuHistorialOrdenes.setToolTipText("Importar el catalogo de productos");
        menuHistorialOrdenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHistorialOrdenesActionPerformed(evt);
            }
        });
        menuBaseDeDatos.add(menuHistorialOrdenes);

        menuCobroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/historialVentas.png"))); // NOI18N
        menuCobroCliente.setText("Cobros Clientes a Excel");
        menuCobroCliente.setToolTipText("");
        menuCobroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCobroClienteActionPerformed(evt);
            }
        });
        menuBaseDeDatos.add(menuCobroCliente);

        menuCobroAreaExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/historialVentas.png"))); // NOI18N
        menuCobroAreaExcel.setText("Cobros Areas a Excel");
        menuCobroAreaExcel.setToolTipText("");
        menuCobroAreaExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCobroAreaExcelActionPerformed(evt);
            }
        });
        menuBaseDeDatos.add(menuCobroAreaExcel);

        menuResumenPropinas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/historialVentas.png"))); // NOI18N
        menuResumenPropinas.setText("Resumen de Propinas");
        menuResumenPropinas.setToolTipText("");
        menuResumenPropinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuResumenPropinasActionPerformed(evt);
            }
        });
        menuBaseDeDatos.add(menuResumenPropinas);

        menuHistorialCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/historialVentas.png"))); // NOI18N
        menuHistorialCompras.setText("Ventas Consolidado");
        menuHistorialCompras.setToolTipText("Importar el catalogo de productos");
        menuHistorialCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHistorialComprasActionPerformed(evt);
            }
        });
        menuBaseDeDatos.add(menuHistorialCompras);

        menu.add(menuBaseDeDatos);

        menuSistema.setText("Sistema");

        menuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/user.png"))); // NOI18N
        menuUsuarios.setText("Usuarios");
        menuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuariosActionPerformed(evt);
            }
        });
        menuSistema.add(menuUsuarios);

        menuParametros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/parametro.png"))); // NOI18N
        menuParametros.setText("Parametros");
        menuParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuParametrosActionPerformed(evt);
            }
        });
        menuSistema.add(menuParametros);

        menuSistemaEstaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/pantalla.png"))); // NOI18N
        menuSistemaEstaciones.setText("Estaciones");
        menuSistemaEstaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSistemaEstacionesActionPerformed(evt);
            }
        });
        menuSistema.add(menuSistemaEstaciones);

        menu.add(menuSistema);

        menuAyuda.setText("Ayuda");

        menuManualDeUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menuManualDeUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/manual.png"))); // NOI18N
        menuManualDeUsuario.setText("Manual de Usuario");
        menuManualDeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManualDeUsuarioActionPerformed(evt);
            }
        });
        menuAyuda.add(menuManualDeUsuario);

        menuAcercaDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        menuAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuickMeal/Imagenes/informacion.png"))); // NOI18N
        menuAcercaDe.setText("Acerca De Inventario");
        menuAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAcercaDeActionPerformed(evt);
            }
        });
        menuAyuda.add(menuAcercaDe);

        menu.add(menuAyuda);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPrincipal)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdEstacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDescripcionEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnProductosMinimo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdEstacion)
                    .addComponent(txtDescripcionEstacion)
                    .addComponent(jLabel4)
                    .addComponent(txtCodigoUsuario)
                    .addComponent(txtNombreUsuario)
                    .addComponent(txtMensaje)
                    .addComponent(btnProductosMinimo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesActionPerformed
        CatalogoAdmonClientes CatalogoClientes = new CatalogoAdmonClientes();
        pnlPrincipal.add(CatalogoClientes);
        CatalogoClientes.setVisible(true);
        CatalogoClientes.toFront();
    }//GEN-LAST:event_menuClientesActionPerformed

    private void menuProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProveedoresActionPerformed
        CatalogoAdmonProveedores CatalogoProveedores = new CatalogoAdmonProveedores();
        pnlPrincipal.add(CatalogoProveedores);
        CatalogoProveedores.setVisible(true);
        CatalogoProveedores.toFront();
    }//GEN-LAST:event_menuProveedoresActionPerformed

    private void menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemActionPerformed
       CatalogoRestauranteItem item = new CatalogoRestauranteItem();
       pnlPrincipal.add(item);
       item.setVisible(true);
       item.toFront();
    }//GEN-LAST:event_menuItemActionPerformed

    private void menuAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAcercaDeActionPerformed
        AyudaAcercaDeInventario AcercaDeInventario = new AyudaAcercaDeInventario();
        pnlPrincipal.add(AcercaDeInventario);
        AcercaDeInventario.setVisible(true);
        AcercaDeInventario.toFront();
    }//GEN-LAST:event_menuAcercaDeActionPerformed

    private void menuCompraDeProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCompraDeProductosActionPerformed
        MovimientoCompraDeProductos CompraDeProductos = new MovimientoCompraDeProductos();
        pnlPrincipal.add(CompraDeProductos);
        CompraDeProductos.setVisible(true);
        CompraDeProductos.toFront();
    }//GEN-LAST:event_menuCompraDeProductosActionPerformed

    private void menuVentaDeProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVentaDeProductosActionPerformed
        CodigoEmpleado nuevo = new CodigoEmpleado();
        pnlPrincipal.add(nuevo);
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (nuevo.getWidth() / 2);
        int y  = (alto / 2) - (nuevo.getHeight() / 2);
        nuevo.setVisible(true);
        nuevo.toFront();
        nuevo.setLocation(x, y);
    }//GEN-LAST:event_menuVentaDeProductosActionPerformed

    private void menuManualDeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManualDeUsuarioActionPerformed

        AyudaManualDeUsuario manual = new AyudaManualDeUsuario();
        manual.setVisible(true);
        pnlPrincipal.add(manual);
        manual.toFront();
    }//GEN-LAST:event_menuManualDeUsuarioActionPerformed

    private void menuReportesInventarioDeProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesInventarioDeProductosActionPerformed
        ReportesInventarioDeProductos inventario = new ReportesInventarioDeProductos();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (inventario.getWidth() / 2);
        int y  = (alto / 2) - (inventario.getHeight() / 2);
        pnlPrincipal.add(inventario);
        inventario.setVisible(true);
        inventario.toFront();
        inventario.setLocation(x, y);
    }//GEN-LAST:event_menuReportesInventarioDeProductosActionPerformed

    private void menuOrdenesActivasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOrdenesActivasActionPerformed
        MovimientoOrdenesActivas OrdenesActivas = new MovimientoOrdenesActivas();
        OrdenesActivas.setVisible(true);
        pnlPrincipal.add(OrdenesActivas);
        OrdenesActivas.toFront();
    }//GEN-LAST:event_menuOrdenesActivasActionPerformed

    private void menuPantallaCocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPantallaCocinaActionPerformed
        try {
            MovimientoPantallaCocina PantallaCocina = new MovimientoPantallaCocina();
            PantallaCocina.setVisible(true);
            pnlPrincipal.add(PantallaCocina);
            PantallaCocina.toFront();
            PantallaCocina.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(QuickMeal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuPantallaCocinaActionPerformed

    private void menuEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmpleadosActionPerformed
        CatalogoAdmonEmpleados Empleados = new CatalogoAdmonEmpleados();
        pnlPrincipal.add(Empleados);
        Empleados.setVisible(true);
        Empleados.toFront();
    }//GEN-LAST:event_menuEmpleadosActionPerformed

    private void menuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosActionPerformed
        CatalogoAdmonProductos Productos = new CatalogoAdmonProductos();
        pnlPrincipal.add(Productos);
        Productos.setVisible(true);
        Productos.toFront();
    }//GEN-LAST:event_menuProductosActionPerformed

    private void menuLotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLotesActionPerformed
        CatalogoAdmonControlDeLotes Lotes = new CatalogoAdmonControlDeLotes();
        pnlPrincipal.add(Lotes);
        Lotes.setVisible(true);
        Lotes.toFront();
    }//GEN-LAST:event_menuLotesActionPerformed

    private void menuCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCategoriaActionPerformed
        CatalogoRestauranteCategorias categoria = new CatalogoRestauranteCategorias();
        pnlPrincipal.add(categoria);
        categoria.setVisible(true);
        categoria.toFront();
    }//GEN-LAST:event_menuCategoriaActionPerformed

    private void menuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuariosActionPerformed
        CatalogoAdmonUsuarios usuario = new CatalogoAdmonUsuarios();
        pnlPrincipal.add(usuario);
        usuario.setVisible(true);
        usuario.toFront();
    }//GEN-LAST:event_menuUsuariosActionPerformed

    private void menuReportesHisComprasClienteDetalladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesHisComprasClienteDetalladoActionPerformed
        ReportesHisComprasClienteDetallado reporte = new ReportesHisComprasClienteDetallado();
        pnlPrincipal.add(reporte);
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) - (reporte.getHeight() / 2);
        reporte.setVisible(true);
        reporte.toFront();
        reporte.setLocation(x, y);
    }//GEN-LAST:event_menuReportesHisComprasClienteDetalladoActionPerformed

    private void menuReportesHIsComprasClienteConsolidadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesHIsComprasClienteConsolidadoActionPerformed
        ReportesHisComprasClienteConsolidado reporte = new ReportesHisComprasClienteConsolidado();
        pnlPrincipal.add(reporte);
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) - (reporte.getHeight() / 2);
        reporte.setVisible(true);
        reporte.toFront();
        reporte.setLocation(x, y);
    }//GEN-LAST:event_menuReportesHIsComprasClienteConsolidadoActionPerformed

    private void menuReportesIngredientesPorFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesIngredientesPorFechaActionPerformed
        ReportesIngredientesUtilizadosFecha reporte = new ReportesIngredientesUtilizadosFecha();
        pnlPrincipal.add(reporte);
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) - (reporte.getHeight() / 2);
        reporte.setVisible(true);
        reporte.toFront();
        reporte.setLocation(x, y);
    }//GEN-LAST:event_menuReportesIngredientesPorFechaActionPerformed

    private void menuReportesProductosMasVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesProductosMasVendidosActionPerformed
        ReportesProductosMasVendidos reporte = new ReportesProductosMasVendidos();
        pnlPrincipal.add(reporte);
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) - (reporte.getHeight() / 2);
        reporte.setVisible(true);
        reporte.toFront();
        reporte.setLocation(x, y);
    }//GEN-LAST:event_menuReportesProductosMasVendidosActionPerformed

    private void menuSistemaEstacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSistemaEstacionesActionPerformed
        SistemaEstaciones estaciones = new SistemaEstaciones();
        pnlPrincipal.add(estaciones);
        estaciones.setVisible(true);
        estaciones.toFront();
    }//GEN-LAST:event_menuSistemaEstacionesActionPerformed

    private void menuServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuServiciosActionPerformed
        CatalogoMiselaneosServicios servicio = new CatalogoMiselaneosServicios();
        pnlPrincipal.add(servicio);
        servicio.setVisible(true);
        servicio.toFront();
    }//GEN-LAST:event_menuServiciosActionPerformed

    private void menuSuscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSuscripcionesActionPerformed
        CatalogoMiselaneosSuscripciones suscripcion = new CatalogoMiselaneosSuscripciones();
        pnlPrincipal.add(suscripcion);
        suscripcion.setVisible(true);
        suscripcion.toFront();
    }//GEN-LAST:event_menuSuscripcionesActionPerformed

    private void menuIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIngredientesActionPerformed
        CatalogoRestauranteIngredientes ingrediente = new CatalogoRestauranteIngredientes();
        pnlPrincipal.add(ingrediente);
        ingrediente.setVisible(true);
        ingrediente.toFront();
    }//GEN-LAST:event_menuIngredientesActionPerformed

    private void menuParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuParametrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuParametrosActionPerformed

    private void menuReportesPlanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesPlanillaActionPerformed
        ReportesPlanillaEmpleados reporte = new ReportesPlanillaEmpleados();
        pnlPrincipal.add(reporte);
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) - (reporte.getHeight() / 2);
        reporte.setVisible(true);
        reporte.toFront();
        reporte.setLocation(x, y);
    }//GEN-LAST:event_menuReportesPlanillaActionPerformed

    private void menuReportesHisComprasClienteDetallado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesHisComprasClienteDetallado1ActionPerformed
        ReportesHistorialComprasPorFecha compras = new ReportesHistorialComprasPorFecha();
        pnlPrincipal.add(compras);
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (compras.getWidth() / 2);
        int y  = (alto / 2) - (compras.getHeight() / 2);
        compras.setVisible(true);
        compras.toFront();
        compras.setLocation(x, y);
    }//GEN-LAST:event_menuReportesHisComprasClienteDetallado1ActionPerformed

    private void menuEditarOrdenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarOrdenesActionPerformed
        MovimientoEditarOrdenes pantalla = new MovimientoEditarOrdenes();
        pnlPrincipal.add(pantalla);
        pantalla.show();
        pantalla.toFront();
    }//GEN-LAST:event_menuEditarOrdenesActionPerformed

    private void menuReportesHisComprasCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesHisComprasCCActionPerformed
        ReportesHisComprasPorCC reporte = new ReportesHisComprasPorCC();
        pnlPrincipal.add(reporte);
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) - (reporte.getHeight() / 2);
        reporte.setVisible(true);
        reporte.toFront();
        reporte.setLocation(x, y);
    }//GEN-LAST:event_menuReportesHisComprasCCActionPerformed

    private void menuReportesHisComprasCC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesHisComprasCC1ActionPerformed
        ReportesHisComprasCredito reporte = new ReportesHisComprasCredito();
        pnlPrincipal.add(reporte);
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) - (reporte.getHeight() / 2);
        reporte.setVisible(true);
        reporte.toFront();
        reporte.setLocation(x, y);
    }//GEN-LAST:event_menuReportesHisComprasCC1ActionPerformed

    private void menuReportesHisComprasClienteDetallado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesHisComprasClienteDetallado2ActionPerformed
        ReportesVentasPorClienteConsolidado reporte = new ReportesVentasPorClienteConsolidado();
        pnlPrincipal.add(reporte);
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) - (reporte.getHeight() / 2);
        reporte.setVisible(true);
        reporte.toFront();
        reporte.setLocation(x, y);
    }//GEN-LAST:event_menuReportesHisComprasClienteDetallado2ActionPerformed

    private void menuReportesReOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesReOrdenActionPerformed
        ReportesReOrden reporte = new ReportesReOrden();
        pnlPrincipal.add(reporte);
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) - (reporte.getHeight() / 2);
        reporte.setVisible(true);
        reporte.toFront();
        reporte.setLocation(x, y);
    }//GEN-LAST:event_menuReportesReOrdenActionPerformed

    private void menuAjusteProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAjusteProductoActionPerformed
        MovimientoAjusteProducto pantalla = new MovimientoAjusteProducto();
        pnlPrincipal.add(pantalla);
        pantalla.show();
        pantalla.toFront();
    }//GEN-LAST:event_menuAjusteProductoActionPerformed

    private void menuReportesCambioPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesCambioPrecioActionPerformed
        ReportesVariacionPrecio reporte = new ReportesVariacionPrecio();
        pnlPrincipal.add(reporte);
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) - (reporte.getHeight() / 2);
        reporte.setVisible(true);
        reporte.toFront();
        reporte.setLocation(x, y);
    }//GEN-LAST:event_menuReportesCambioPrecioActionPerformed

    private void btnProductosMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosMinimoActionPerformed
        try{
            Conexion acceso = new Conexion();
            URL url_reporte = this.getClass().getResource("/QuickMeal/Reportes/PuntoDeReOrden.jasper");
            JasperReport reporte = (JasperReport) JRLoader.loadObject(url_reporte);
            HashMap parametro = new HashMap();
            JasperPrint pantalla = JasperFillManager.fillReport(reporte, parametro, acceso.conectar());
            JasperViewer visualizador = new JasperViewer(pantalla, false);
            visualizador.show();
        }catch(Exception error){
        }
    }//GEN-LAST:event_btnProductosMinimoActionPerformed

    private void menuResumenPropinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuResumenPropinasActionPerformed
        BaseDeDatosCobrosPropinas pantalla = new BaseDeDatosCobrosPropinas();
        pnlPrincipal.add(pantalla);
        pantalla.show();
        pantalla.toFront();
    }//GEN-LAST:event_menuResumenPropinasActionPerformed

    private void menuCobroAreaExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCobroAreaExcelActionPerformed
        BaseDeDatosCobrosAreas pantalla = new BaseDeDatosCobrosAreas();
        pnlPrincipal.add(pantalla);
        pantalla.show();
        pantalla.toFront();
    }//GEN-LAST:event_menuCobroAreaExcelActionPerformed

    private void menuCobroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCobroClienteActionPerformed
        BaseDeDatosCobrosSocios pantalla = new BaseDeDatosCobrosSocios();
        pnlPrincipal.add(pantalla);
        pantalla.show();
        pantalla.toFront();
    }//GEN-LAST:event_menuCobroClienteActionPerformed

    private void menuHistorialComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHistorialComprasActionPerformed
        BaseDeDatosHistorialCompras pantalla = new BaseDeDatosHistorialCompras();
        pnlPrincipal.add(pantalla);
        pantalla.show();
        pantalla.toFront();
    }//GEN-LAST:event_menuHistorialComprasActionPerformed

    private void menuHistorialOrdenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHistorialOrdenesActionPerformed
        BaseDeDAtosHistorialDeVentas pantalla = new BaseDeDAtosHistorialDeVentas();
        QuickMeal.pnlPrincipal.add(pantalla);
        pantalla.show();
    }//GEN-LAST:event_menuHistorialOrdenesActionPerformed

    private void menuImportarCatalogoDeProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuImportarCatalogoDeProductosActionPerformed
        BaseDeDatosImportarCatalogoDeProductos importar = new BaseDeDatosImportarCatalogoDeProductos();
        pnlPrincipal.add(importar);
        importar.setVisible(true);
        importar.toFront();
    }//GEN-LAST:event_menuImportarCatalogoDeProductosActionPerformed

    private void menuExportarCatalogoDeProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExportarCatalogoDeProductosActionPerformed
        BaseDeDatosExportarCatalogoDeProductos exportar = new BaseDeDatosExportarCatalogoDeProductos();
        pnlPrincipal.add(exportar);
        exportar.setVisible(true);
        exportar.toFront();
    }//GEN-LAST:event_menuExportarCatalogoDeProductosActionPerformed

    private void menuHistorialCompraProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHistorialCompraProductosActionPerformed
        BaseDeDatosHistorialCompraProductos exportar = new BaseDeDatosHistorialCompraProductos();
        pnlPrincipal.add(exportar);
        exportar.setVisible(true);
        exportar.toFront();
   }//GEN-LAST:event_menuHistorialCompraProductosActionPerformed

    private void menuReportesCierreDiarioCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesCierreDiarioCajaActionPerformed
        ReportesCierreDiarioCaja reporte = new ReportesCierreDiarioCaja();
        pnlPrincipal.add(reporte);
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        int x  = (ancho / 2) - (reporte.getWidth() / 2);
        int y  = (alto / 2) - (reporte.getHeight() / 2);
        reporte.setVisible(true);
        reporte.toFront();
        reporte.setLocation(x, y);
    }//GEN-LAST:event_menuReportesCierreDiarioCajaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuickMeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuickMeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuickMeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuickMeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuickMeal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnProductosMinimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    public static javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem menuAcercaDe;
    private javax.swing.JMenu menuAdministracion;
    public static javax.swing.JMenuItem menuAjusteProducto;
    public static javax.swing.JMenu menuAyuda;
    public static javax.swing.JMenu menuBaseDeDatos;
    public static javax.swing.JMenu menuCatalogo;
    public static javax.swing.JMenuItem menuCategoria;
    private javax.swing.JMenuItem menuClientes;
    public static javax.swing.JMenuItem menuCobroAreaExcel;
    public static javax.swing.JMenuItem menuCobroCliente;
    public static javax.swing.JMenuItem menuCompraDeProductos;
    public static javax.swing.JMenuItem menuEditarOrdenes;
    public static javax.swing.JMenuItem menuEmpleados;
    public static javax.swing.JMenuItem menuExportarCatalogoDeProductos;
    public static javax.swing.JMenuItem menuHistorialCompraProductos;
    public static javax.swing.JMenuItem menuHistorialCompras;
    public static javax.swing.JMenuItem menuHistorialOrdenes;
    public static javax.swing.JMenuItem menuImportarCatalogoDeProductos;
    public static javax.swing.JMenuItem menuIngredientes;
    public static javax.swing.JMenuItem menuItem;
    public static javax.swing.JMenuItem menuLotes;
    private javax.swing.JMenuItem menuManualDeUsuario;
    public static javax.swing.JMenu menuMiselaneos;
    public static javax.swing.JMenu menuMovimiento;
    public static javax.swing.JMenuItem menuOrdenesActivas;
    public static javax.swing.JMenuItem menuPantallaCocina;
    private javax.swing.JMenuItem menuParametros;
    public static javax.swing.JMenuItem menuProductos;
    public static javax.swing.JMenuItem menuProveedores;
    public static javax.swing.JMenu menuReportes;
    private javax.swing.JMenuItem menuReportesCambioPrecio;
    private javax.swing.JMenuItem menuReportesCierreDiarioCaja;
    private javax.swing.JMenuItem menuReportesHIsComprasClienteConsolidado;
    public static javax.swing.JMenuItem menuReportesHisComprasCC;
    public static javax.swing.JMenuItem menuReportesHisComprasCC1;
    private javax.swing.JMenuItem menuReportesHisComprasClienteDetallado;
    private javax.swing.JMenuItem menuReportesHisComprasClienteDetallado1;
    private javax.swing.JMenuItem menuReportesHisComprasClienteDetallado2;
    private javax.swing.JMenuItem menuReportesIngredientesPorFecha;
    private javax.swing.JMenuItem menuReportesInventarioDeProductos;
    public static javax.swing.JMenuItem menuReportesPlanilla;
    private javax.swing.JMenuItem menuReportesProductosMasVendidos;
    public static javax.swing.JMenuItem menuReportesReOrden;
    private javax.swing.JMenu menuRestaurante;
    public static javax.swing.JMenuItem menuResumenPropinas;
    private javax.swing.JMenuItem menuServicios;
    public static javax.swing.JMenu menuSistema;
    private javax.swing.JMenuItem menuSistemaEstaciones;
    private javax.swing.JMenuItem menuSuscripciones;
    private javax.swing.JMenuItem menuUsuarios;
    public static javax.swing.JMenuItem menuVentaDeProductos;
    public static javax.swing.JDesktopPane pnlPrincipal;
    public static javax.swing.JLabel txtCodigoUsuario;
    private static javax.swing.JLabel txtDescripcionEstacion;
    private static javax.swing.JLabel txtIdEstacion;
    private javax.swing.JLabel txtMensaje;
    private static javax.swing.JLabel txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
